### ISSUE TITLE
Data differences for sidebar labels between client and server

### ISSUE THREAD

**Issue by pixelass** [patternplate/patternplate#168] opened 2018-03-13 11:00 UTC
related? #163 

Inconsistencies cause issues when trying to use certain features (e.g. sidebar-toggle)

![pp2-issue](https://user-images.githubusercontent.com/1148334/37337862-e0b59022-26b5-11e8-99af-8a4e5de94cb2.gif)

```
vendors.js:24365 Warning: Prop `href` did not match. Server: "/?rjnpaxrkz-enabled=true" Client: "/?ryswrxrtg-enabled=true"
printWarning @ vendors.js:24365
warning @ vendors.js:24389
warnForPropDifference @ vendors.js:60651
diffHydratedProperties$1 @ vendors.js:61373
hydrateInstance @ vendors.js:62086
prepareToHydrateHostInstance @ vendors.js:56560
completeWork @ vendors.js:55608
completeUnitOfWork @ vendors.js:57105
performUnitOfWork @ vendors.js:57207
workLoop @ vendors.js:57261
callCallback @ vendors.js:47515
invokeGuardedCallbackDev @ vendors.js:47554
invokeGuardedCallback @ vendors.js:47411
renderRoot @ vendors.js:57339
performWorkOnRoot @ vendors.js:57987
performWork @ vendors.js:57940
requestWork @ vendors.js:57851
scheduleWorkImpl @ vendors.js:57705
scheduleWork @ vendors.js:57662
scheduleTopLevelUpdate @ vendors.js:58166
updateContainer @ vendors.js:58204
(anonymous) @ vendors.js:62199
unbatchedUpdates @ vendors.js:58075
renderSubtreeIntoContainer @ vendors.js:62198
hydrate @ vendors.js:62260
_default @ client.js:5937
(anonymous) @ client.js:5836
(anonymous) @ client.js:9860
Promise.then (async)
(anonymous) @ client.js:5829
boundThen @ client.js:9868
main @ client.js:5825
(anonymous) @ client.js:5820
Object.defineProperty.value @ client.js:5885
__webpack_require__ @ vendors.js:55
webpackJsonpCallback @ vendors.js:26
(anonymous) @ client.js:1
```

**Comment by marionebl** [comment] 2018-03-13 12:44
I think this is independent of #163, caused by the fallback ids for docs being calculated differently on server and client.

**Comment by marionebl** [comment] 2018-03-17 20:24
Virtual folders compute stable names for usage in as `[name]-enabled` query parameter now, so this specific issue should be fixed/mitigated.

**Closed by marionebl** 2018-03-17 20:24 UTC
Labels: bug
